src/Entity/Achats.php
<?php

namespace App\Entity;

use App\Entity\Categories;
use App\Entity\Trait\SlugTrait;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\AchatsRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
//use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AchatsRepository::class)]
class Achats
{
    use SlugTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $lieu_achat;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_produit;

    #[ORM\ManyToOne(inversedBy: 'achats', targetEntity: Categories::class)]
    private $categorie;

    #[ORM\Column(type: 'date')]
    private $date_achat;

    #[ORM\Column(type: 'date')]
    private $fin_garantie;

    #[ORM\Column(type: 'float')]
    private $prix;

    #[ORM\Column(type: 'text')]
    private $informations;

    #[ORM\Column(type: 'string', length: 255)]
    private $ticket_achat;

    
    #[ORM\OneToMany(mappedBy: 'achats', targetEntity: PhotoFactures::class, orphanRemoval: true)]
    private $photoFactures;

    #[ORM\OneToMany(mappedBy: 'achats', targetEntity: Images::class, orphanRemoval: true)]
    private $images;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $manuel_utilisation;

    public function __construct()
    {
        $this->photoFactures = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLieuAchat(): ?string
    {
        return $this->lieu_achat;
    }

    public function setLieuAchat(string $lieu_achat): self
    {
        $this->lieu_achat = $lieu_achat;

        return $this;
    }

    public function getNomProduit(): ?string
    {
        return $this->nom_produit;
    }

    public function setNomProduit(string $nom_produit): self
    {
        $this->nom_produit = $nom_produit;

        return $this;
    }

    public function getCategorie(): ?Categories
    {
        return $this->categorie;
    }

    public function setCategorie(?Categories $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getDateAchat(): ?\DateTime
    {
        return $this->date_achat;
    }

    public function setDateAchat(\DateTime $date_achat): self
    {
        $this->date_achat = $date_achat;

        return $this;
    }

    public function getFinGarantie(): ?\DateTimeInterface
    {
        return $this->fin_garantie;
    }

    public function setFinGarantie(\DateTimeInterface $fin_garantie): self
    {
        $this->fin_garantie = $fin_garantie;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getInformations(): ?string
    {
        return $this->informations;
    }

    public function setInformations(string $informations): self
    {
        $this->informations = $informations;

        return $this;
    }

    public function getTicketAchat(): ?string
    {
        return $this->ticket_achat;
    }

    public function setTicketAchat(string $ticket_achat): self
    {
        $this->ticket_achat = $ticket_achat;

        return $this;
    }



    public function getCategories(): ?Categories
    {
        return $this->categories;
    }

    /*public function (?Categories $categories): self
    {
        $this->categories = $categories;

        return $this;
    }*/

    /**
     * @return Collection<int, PhotoFactures>
     */
    public function getPhotoFactures(): Collection
    {
        return $this->photoFactures;
    }

    public function addPhotoFacture(PhotoFactures $photoFacture): self
    {
        if (!$this->photoFactures->contains($photoFacture)) {
            $this->photoFactures[] = $photoFacture;
            $photoFacture->setAchats($this);
        }

        return $this;
    }

    public function removePhotoFacture(PhotoFactures $photoFacture): self
    {
        if ($this->photoFactures->removeElement($photoFacture)) {
            // set the owning side to null (unless already changed)
            if ($photoFacture->getAchats() === $this) {
                $photoFacture->setAchats(null);
            }
        }

        return $this;
    }

   /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAchats($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAchats() === $this) {
                $image->setAchats(null);
            }
        }

        return $this;
    }

    public function getManuelUtilisation(): ?string
    {
        return $this->manuel_utilisation;
    }

    public function setManuelUtilisation(?string $manuel_utilisation): self
    {
        $this->manuel_utilisation = $manuel_utilisation;

        return $this;
    }
}

templates/tableau_de_bord/achats.html.twig
{% extends 'base.html.twig' %}

{% block title %}Achats{% endblock %}

{% block main %}
<section>
    <figure>
        <figcaption class="ligne ecartee">
            <h1>Liste des achats</h1>
            <nav>
                <a info-bulle="Ajouter" href="{{ path('ajout_achat') }}"><img class="icone" src="{{ asset('images/ajout.svg') }}" alt="Ajouter"></a>
            </nav>
        </figcaption>
        <table>
            <tr>
                <th>Nom</th>
                <th>Catégorie</th>
                <th>Lieu d'achat</th>
                <th>Date d'achat</th>
                <th>Fin de garantie</th>
                <th>Prix</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            {% for achat in achats %}
                <tr>
                    <th>{{ achat.nomProduit }}</th>
                    <td>
                        {{ achat.categorie }}
                    </td>
                    <td>{{ achat.lieuAchat }}</td>
                    <td>{{ achat.dateAchat|date('d/m/Y') }}</td>
                    <td>{{ achat.finGarantie|date('d/m/Y') }}</td>
                    <td>{{ achat.prix }} €</td>
                    <td class="lien"><a href="{{ path('visualisation_achat', {'id': achat.id}) }}"><img class="icone" src="{{ asset('images/visualisation.svg') }}" alt="Visualiser"></a></td>
                    <td class="lien"><a href="{{ path('modification_achat', {'id': achat.id}) }}"><img class="icone" src="{{ asset('images/edition.svg') }}" alt="Éditer"></a></td>
                    <td class="lien"><a href="{{ path('suppression_achat', {'id': achat.id}) }}"><img class="icone" src="{{ asset('images/suppression.svg') }}" alt="Supprimer"></a></td>
                </tr>
            {% endfor %}
        </table>
    </figure>
</section>
{% endblock %}

templates/tableau_de_bord/ajout_achat.html.twig
{% extends 'base.html.twig' %}

{% form_theme form_ajout_achat 'bootstrap_5_layout.html.twig' %}

{% block title %}Ajouter un achat{% endblock %}

{% block main %}
    <section>
        <figure>
            <figcaption>
                <h1>Ajouter un achat</h1>
            </figcaption>

            {{ form_start(form_ajout_achat) }}

                {{ form_row(form_ajout_achat.nom_produit, {'label': 'Nom'}) }}
                <div class="ligne ecartee v-centree">
                    {{ form_row(form_ajout_achat.categorie, {'label': 'Catégorie'}) }}
                    <nav>
                        <a info-bulle="Ajouter" href="{{ path('ajout_categorie') }}"><img class="icone" src="{{ asset('images/ajout.svg') }}" alt="Ajouter"></a>
                    </nav>
                </div>
                {{ form_row(form_ajout_achat.informations, {'label': 'Informations sur le produit'}) }}
                {{ form_row(form_ajout_achat.lieu_achat, {'label': 'Lieu d\'achat'}) }}
                {{ form_row(form_ajout_achat.date_achat, {'label': 'Date d\'achat'}) }}
                {{ form_row(form_ajout_achat.fin_garantie, {'label': 'Date de fin de garantie'}) }}
                {{ form_row(form_ajout_achat.prix, {'label': 'Prix en €'}) }}
                {{ form_row(form_ajout_achat.ticket_achat, {'label': 'Ticket d\'achat'}) }}
                {{ form_row(form_ajout_achat.manuel_utilisation, {'label': 'Manuel d\'utilisation'}) }}

                <button type="submit" class="btn btn-success">Ajouter l'achat</button>

            {{ form_end(form_ajout_achat) }}

        </figure>
    </section>
{% endblock %}

templates/tableau_de_bord/ajout_categorie.html.twig
{% extends 'base.html.twig' %}

{% form_theme form_ajout_categorie 'bootstrap_5_layout.html.twig' %}

{% block title %}Ajouter une catégorie{% endblock %}

{% block main %}
    <section>
        <figure>
            <figcaption>
                <h1>Ajouter une catégorie d'achats</h1>
            </figcaption>

            {{ form_start(form_ajout_categorie) }}

                {{ form_row(form_ajout_categorie.name, {'label': 'Nom'}) }}
                <div class="ligne ecartee v-centree">
                    {{ form_row(form_ajout_categorie.parent, {'label': 'Secteur d\'activité'}) }}
                    <nav>
                        <a info-bulle="Ajouter" href="{{ path('ajout_secteur') }}"><img class="icone" src="{{ asset('images/ajout.svg') }}" alt="Ajouter"></a>
                    </nav>
                </div>

                <button type="submit" class="btn btn-success">Ajouter la catégorie</button>

            {{ form_end(form_ajout_categorie) }}

        </figure>
    </section>
{% endblock %}

templates/tableau_de_bord/ajout_secteur.html.twig
{% extends 'base.html.twig' %}

{% form_theme form_ajout_secteur 'bootstrap_5_layout.html.twig' %}

{% block title %}Ajouter un secteur{% endblock %}

{% block main %}
    <section>
        <figure>
            <figcaption>
                <h1>Ajouter un secteur d'activité</h1>
            </figcaption>

            {{ form_start(form_ajout_secteur) }}

                {{ form_row(form_ajout_secteur.name, {'label': 'Nom'}) }}

                <button type="submit" class="btn btn-success">Ajouter le secteur</button>

            {{ form_end(form_ajout_secteur) }}

        </figure>
    </section>
{% endblock %}

templates/tableau_de_bord/categories.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catégories{% endblock %}

{% block main %}
<section>
    <figure>
        <figcaption class="ligne ecartee">
            <h1>Liste des secteurs d'activité</h1>
            <nav>
                <a info-bulle="Ajouter" href="{{ path('ajout_secteur') }}"><img class="icone" src="{{ asset('images/ajout.svg') }}" alt="Ajouter"></a>
            </nav>
        </figcaption>
        <table>
            <tr>
                <th>Nom</th>
                <th>Nombre de catégories</th>
                <th></th>
                <th></th>
            </tr>
            {% for secteur in categories %}
                {% if secteur.parent == NULL %}
                    <tr>
                        <th>{{ secteur.name }}</th>
                        <td>
                            {% set nombre_categories = 0 %}
                            {% for categorie in categories %}
                                {% if categorie.parent != NULL and categorie.parent.id == secteur.id %}
                                    {% set nombre_categories = nombre_categories + 1 %}
                                {% endif %}
                            {% endfor %}
                            {{ nombre_categories }}
                        </td>
                        <td class="lien"><a href="{{ path('modification_secteur', {'id': secteur.id}) }}"><img class="icone" src="{{ asset('images/edition.svg') }}" alt="Éditer"></a></td>
                        <td class="lien"><a href="{{ path('suppression_categorie', {'id': secteur.id}) }}"><img class="icone" src="{{ asset('images/suppression.svg') }}" alt="Supprimer"></a></td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
    </figure>

    <figure>
        <figcaption class="ligne ecartee">
            <h1>Liste des catégories</h1>
            <nav>
                <a info-bulle="Ajouter" href="{{ path('ajout_categorie') }}"><img class="icone" src="{{ asset('images/ajout.svg') }}" alt="Ajouter"></a>
            </nav>
        </figcaption>
        <table>
            <tr>
                <th>Nom</th>
                <th>Secteur d'activité</th>
                <th>Nombre d'achats</th>
                <th></th>
                <th></th>
            </tr>
            {% for categorie in categories %}
                {% if categorie.parent != NULL %}
                    <tr>
                        <th>{{ categorie.name }}</th>
                        <td>{{ categorie.parent.name }}</td>
                        <td>
                            {% set nombre_achats = 0 %}
                            {% for achat in achats %}
                                {% if achat.categorie.id == categorie.id %}
                                    {% set nombre_achats = nombre_achats + 1 %}
                                {% endif %}
                            {% endfor %}
                            {{ nombre_achats }}
                        </td>
                        <td class="lien"><a href="{{ path('modification_categorie', {'id': categorie.id}) }}"><img class="icone" src="{{ asset('images/edition.svg') }}" alt="Éditer"></a></td>
                        <td class="lien"><a href="{{ path('suppression_categorie', {'id': categorie.id}) }}"><img class="icone" src="{{ asset('images/suppression.svg') }}" alt="Supprimer"></a></td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
    </figure>
</section>
{% endblock %}

templates/tableau_de_bord/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tableau de bord{% endblock %}

{% block main %}
    <section>
        <h1>Accueil du tableau de bord</h1>
    </section>
{% endblock %}

templates/tableau_de_bord/modification_achat.html.twig
{% extends 'base.html.twig' %}

{% form_theme form_modification_achat 'bootstrap_5_layout.html.twig' %}

{% block title %}Modifier un achat{% endblock %}

{% block main %}
    <section>
        <figure>
        <figcaption>
            <h1>Modifier l'achat n<sup>o</sup> {{ id }}</h1>
        </figcaption>

            {{ form_start(form_modification_achat) }}

                {{ form_row(form_modification_achat.nom_produit, {'label': 'Nom'}) }}
                {{ form_row(form_modification_achat.categorie, {'label': 'Catégorie'}) }}
                {{ form_row(form_modification_achat.informations, {'label': 'Informations sur le produit'}) }}
                {{ form_row(form_modification_achat.lieu_achat, {'label': 'Lieu d\'achat'}) }}
                {{ form_row(form_modification_achat.date_achat, {'label': 'Date d\'achat'}) }}
                {{ form_row(form_modification_achat.fin_garantie, {'label': 'Date de fin de garantie'}) }}
                {{ form_row(form_modification_achat.prix, {'label': 'Prix en €'}) }}
                {{ form_row(form_modification_achat.ticket_achat, {'label': 'Ticket d\'achat'}) }}
                {{ form_row(form_modification_achat.manuel_utilisation, {'label': 'Manuel d\'utilisation'}) }}

                <button type="submit" class="btn btn-success">Modifier l'achat</button>

            {{ form_end(form_modification_achat) }}
        </figure>
    </section>
{% endblock %}

templates/tableau_de_bord/modification_categorie.html.twig
{% extends 'base.html.twig' %}

{% form_theme form_modification_categorie 'bootstrap_5_layout.html.twig' %}

{% block title %}Modifier une catégorie{% endblock %}

{% block main %}
    <section>
        <figure>
        <figcaption>
            <h1>Modifier la catégorie d'achats n<sup>o</sup> {{ id }}</h1>
        </figcaption>

            {{ form_start(form_modification_categorie) }}

                {{ form_row(form_modification_categorie.name, {'label': 'Nom'}) }}
                {{ form_row(form_modification_categorie.parent, {'label': 'Secteur d\'activité'}) }}

                <button type="submit" class="btn btn-success">Modifier la catégorie</button>

            {{ form_end(form_modification_categorie) }}
        </figure>
    </section>
{% endblock %}

templates/tableau_de_bord/modification_secteur.html.twig
{% extends 'base.html.twig' %}

{% form_theme form_modification_secteur 'bootstrap_5_layout.html.twig' %}

{% block title %}Modifier un secteur{% endblock %}

{% block main %}
    <section>
        <figure>
        <figcaption>
            <h1>Modifier le secteur d'activité n<sup>o</sup> {{ id }}</h1>
        </figcaption>

            {{ form_start(form_modification_secteur) }}

                {{ form_row(form_modification_secteur.name, {'label': 'Nom'}) }}

                <button type="submit" class="btn btn-success">Modifier le secteur</button>

            {{ form_end(form_modification_secteur) }}
        </figure>
    </section>
{% endblock %}

templates/tableau_de_bord/statistiques.html.twig
{% extends 'base.html.twig' %}

{% block title %}Statistiques{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock %}

{% block main %}
    <section>
        {% if statistiques %}
            <figure>
                <figcaption>
                    <h1>Comparaison des sommes dépensées par secteur du {{ periode.debut|date('d/m/Y') }} au {{ periode.fin|date('d/m/Y') }}</h1>
                </figcaption>
                <div class="chart-container graphique">
                    <canvas id="myChart"></canvas>
                </div>
                <script>
                const ctx = document.getElementById('myChart');
                const myChart = new Chart(ctx, {
                    type: 'pie',
                    data: {
                        labels: [
                            {% for categorie in statistiques %}
                                '{{ categorie.nom }} ',
                            {% endfor %}
                        ],
                        datasets: [{
                            label: 'Sommes dépensées par secteurs',
                            data: [
                                {% for categorie in statistiques %}
                                    {{ categorie.somme_depensee }},
                                {% endfor %}
                            ],
                            backgroundColor: [
                                {% for categorie in statistiques %}
                                    'hsla({{ categorie.teinte }}, 80%, 50%, 0.2)',
                                {% endfor %}
                            ],
                            borderColor: [
                                {% for categorie in statistiques %}
                                    'hsla({{ categorie.teinte }}, 80%, 50%, 1)',
                                {% endfor %}
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        maintainAspectRatio: false,
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        }
                    }
                });
                </script>
            </figure>
        {% endif %}

        <figure>
            <figcaption>
                <h1>Sur quelle période voulez-vous étudier les sommes dépensées ?</h1>
            </figcaption>

            {{ form_start(form_periode) }}

                <div class="ligne ecartee">
                    {{ form_row(form_periode.debut_periode, {'label': 'Date de début'}) }}
                    {{ form_row(form_periode.fin_periode, {'label': 'Date de fin'}) }}

                    <button type="submit" class="btn btn-success">Afficher le graphique</button>
                </div>

                {{ form_row(form_periode.secteurs, {'label': 'Afficher les secteurs d\'activité'})}}

            {{ form_end(form_periode) }}
        </figure>
    </section>
{% endblock %}

templates/tableau_de_bord/suppression_achat.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supprimer un achat{% endblock %}

{% block main %}
    <section>
        <h1>Voulez-vous vraiment supprimer l'achat n<sup>o</sup> {{ id }} ?</h1>
        <nav class="ligne">
            <a info-bulle="Valider" href="{{ path('suppression_achat_valide', {'id': id}) }}"><img class="icone" src="{{ asset('images/valider.svg') }}" alt="Valider"></a>
            <a info-bulle="Annuler" href="{{ path('achats') }}"><img class="icone" src="{{ asset('images/annuler.svg') }}" alt="Annuler"></a>
        </nav>
    </section>
{% endblock %}

templates/tableau_de_bord/suppression_categorie.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% if type == 'secteur' %}
        Supprimer un secteur
    {% else %}
        Supprimer une catégorie
    {% endif %}
{% endblock %}

{% block main %}
    <section>
        {% if suppression_impossible == 0 %}
            {% if type == 'secteur' %}
                <h1>Voulez-vous vraiment supprimer le secteur d'activité n<sup>o</sup> {{ id }} ?</h1>
            {% else %}
                <h1>Voulez-vous vraiment supprimer la catégorie d'achats n<sup>o</sup> {{ id }} ?</h1>
            {% endif %}
            <nav class="ligne">
                <a info-bulle="Valider" href="{{ path('suppression_categorie_valide', {'id': id}) }}"><img class="icone" src="{{ asset('images/valider.svg') }}" alt="Valider"></a>
                <a info-bulle="Annuler" href="{{ path('categories') }}"><img class="icone" src="{{ asset('images/annuler.svg') }}" alt="Annuler"></a>
            </nav>
        {% else %}
            {% if type == 'secteur' %}
                <h1>Vous ne pouvez pas supprimer ce secteur : il contient {{ suppression_impossible }} catégorie{% if suppression_impossible > 1 %}s{% endif %}.</h1>
            {% else %}
                <h1>Vous ne pouvez pas supprimer cette catégorie : elle contient {{ suppression_impossible }} achat{% if suppression_impossible > 1 %}s{% endif %}.</h1>
            {% endif %}
            <nav class="ligne">
                <a info-bulle="Retour" href="{{ path('categories')}}"><img class="icone" src="{{ asset('images/retour.svg') }}" alt="Retour"></a>
                    {% if type == 'secteur' %}
                        <a info-bulle="Éditer" href="{{ path('modification_secteur', {'id': id}) }}"><img class="icone" src="{{ asset('images/edition.svg') }}" alt="Éditer"></a>
                    {% else %}
                        <a info-bulle="Éditer" href="{{ path('modification_categorie', {'id': id}) }}"><img class="icone" src="{{ asset('images/edition.svg') }}" alt="Éditer"></a>
                    {% endif %}
            </nav>
        {% endif %}
    </section>
{% endblock %}

templates/tableau_de_bord/visualisation_achat.html.twig
{% extends 'base.html.twig' %}

{% block title %}Visualiser un achat{% endblock %}

{% block main %}
<section>
    <figure>
        <figcaption class="ligne ecartee">
            <h1>Achat n<sup>o</sup> {{ achat.id }}</h1>
            <nav>
                <a href="{{ path('modification_achat', {'id': achat.id}) }}"><img class="icone" src="{{ asset('images/edition.svg') }}" alt="Éditer"></a>
                <a href="{{ path('suppression_achat', {'id': achat.id}) }}"><img class="icone" src="{{ asset('images/suppression.svg') }}" alt="Supprimer"></a>
            </nav>
        </figcaption>
        <table>
            <tr>
                <th>Nom</th>
                <td>{{ achat.nomProduit }}</td>
            </tr>
            <tr>
                <th>Catégorie</th>
                <td>{{ achat.categorie }}</td>
            </tr>
            <tr>
                <th>Lieu d'achat</th>
                <td>{{ achat.lieuAchat }}</td>
            </tr>
            <tr>
                <th>Date d'achat</th>
                <td>{{ achat.dateAchat|date('d/m/Y') }}</td>
            </tr>
            <tr>
                <th>Fin de garantie</th>
                <td>{{ achat.finGarantie|date('d/m/Y') }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ achat.prix }} €</td>
            </tr>
            <tr>
                <th>Informations</th>
                <td>{{ achat.informations }}</td>
            </tr>
            <tr>
                <th>Ticket d'achat</th>
                <td><img src="{{ asset('donnees/tickets/' ~ achat.ticketAchat) }}" alt="Ticket d'achat n° {{ achat.id }}"></td>
            </tr>
            {% if achat.manuelUtilisation != NULL %}
                <tr>
                    <th>Manuel d'utilisation</th>
                    <td><a href="{{ asset('donnees/manuels/' ~ achat.manuelUtilisation) }}" target="_blank">Voir le manuel d'utilisation</a></td>
                </tr>
            {% endif %}
        </table>
    </figure>
</section>
{% endblock %}